---
- name: Create EC2 instances
  amazon.aws.ec2_instance:
    name: "{{ instance_name }}"
    key_name: "{{ key_name }}"
    region: "{{ region_name }}"
    image_id: "{{ ami_id }}"
    vpc_subnet_id: "{{ random_subnet }}"
    instance_type: "{{ instance_type }}"
    security_group: "{{ security_group.group_id | default('default') }}"
    tags:
      Env: Testing
      launcher: ansible
    network:
      assign_public_ip: true
  register: ec2

- name: Print info about created instance
  ansible.builtin.debug:
    msg:
#      - "Instance: {{ ec2 }}"
      - "Instance ID: {{ ec2.instances[0]['instance_id'] }}"
      - "Key Name: {{ ec2.instances[0].key_name }}"
      - "Private IP: {{ ec2.instances[0].private_ip_address }}"
