---
- name: Create a new EC2 key pair
  amazon.aws.ec2_key:
    name: "{{ key_name }}"
    key_type: "{{ key_type }}"
    region: "{{ region_name }}"
  register: ec2_key

- name: Save private key
  copy: 
    content: "{{ ec2_key.key.private_key }}"
    dest: "./keys/{{ key_name }}.pem"
    mode: 0400
  when: ec2_key.changed
