---
- name: Create Security Group
  amazon.aws.ec2_group:
    name: "{{ security_group_name }}"
    description: "Ansible managed security group" 
    vpc_id: "{{ vpc_id }}"
    region: "{{ region_name }}"
    rules:
      - proto: tcp
        ports:
          - 22
        cidr_ip: "0.0.0.0/0"
        rule_desc: "allow port 22 from world"
  when: security_group_name | length > 0
  register: security_group
